### ISSUE TITLE
sixDoF problems

### ISSUE THREAD

**Issue by robertsawko** [smenon/dynamicTopoFvMesh#4]
Hello Sandeep,

together with a colleague of mine we're trying to run your port on 2.2.x with sixDoFDisplacement boundary condition.

We run in two configurations with and without usePointDisplacement.

a) Without usePointDisplacement in mesquiteOptions

In this case we're providing boundary setup in mesquiteOptions. We can see that the code works, velocities get recalculated, mesh moves etc, etc. But for the purpose of mesh movmemt only the initial value of velocity and angular momentum is used. We believe that this is tied to the fact that in this configuration sixDoF is essentially being reconstructed on each time step. This is evident here

``` c++
            autoPtr<pointPatchField<point> > pField
            (
                pointPatchField<point>::New
                (
                    pMesh.boundary()[patchI],
                    dPointField,
                    fvpDict.subDict(fixPatches[wordI])
                )
            );

            pField().updateCoeffs();

```

b) With usePointDisplacement

something goes seriously wrong when moving from one time step to another. When we print the fields it looks that boundaryField of pointVectorField is somehow lost. This usally results in errors of this form

```
#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::sigSegv::sigHandler(int) at ??:?
#2   in "/usr/lib/libc.so.6"
#3  Foam::GeometricField<Foam::Vector<double>, Foam::pointPatchField, Foam::pointMesh>::GeometricBoundaryField::writeEntry(Foam::word const&, Foam::Ostream&) const at ??:?
#4  Foam::GeometricField<Foam::Vector<double>, Foam::pointPatchField, Foam::pointMesh>::writeData(Foam::Ostream&) const at ??:?
#5  Foam::regIOobject::writeObject(Foam::IOstream::streamFormat, Foam::IOstream::versionNumber, Foam::IOstream::compressionType) const at ??:?
#6  Foam::objectRegistry::writeObject(Foam::IOstream::streamFormat, Foam::IOstream::versionNumber, Foam::IOstream::compressionType) const at ??:?
#7  Foam::objectRegistry::writeObject(Foam::IOstream::streamFormat, Foam::IOstream::versionNumber, Foam::IOstream::compressionType) const at ??:?
#8  Foam::Time::writeObject(Foam::IOstream::streamFormat, Foam::IOstream::versionNumber, Foam::IOstream::compressionType) const at ??:?
#9  
```

You can suppress that by specifying that this is not written to the file, but this will result in further errors which are tied to missing boundaryField.

We would appreciate your advice on how to fix that issue. In theory this should be made to work in a smilar fashion like pointDisplacementMotionSolver from standard distribution, but somehow we were unable to find the difference that makes one code pass pointDisplacement BCs to the next time step.

Thanks,
Robert

**Comment by mojtabaAmiraslanpour** [comment]
Hi,
I am very interested in this problem, unfortunately I couldn't download the test case file attached above. Its probably deleted.
Is it possible to re-upload the test case and give a short description about the hack discussed above?

Thank you.

**Comment by RupeshW** [comment]
Hello Sandeep,
I recently came across "dynamicTopoFvMesh"  as i installed foam extend 3.1 (also read some of the documents available online, mostly written by you.), but still not sure about how it works, 
So can you please share any simple test/tutorial case, so that it will be easy to understand.
